// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC7wdXZrTzI0ztV1loBY8wohZ9hFGpdh3A',
    appId: '1:153738262076:web:c5c2c1821be64b9378b539',
    messagingSenderId: '153738262076',
    projectId: 'threadup-ae501',
    authDomain: 'threadup-ae501.firebaseapp.com',
    storageBucket: 'threadup-ae501.firebasestorage.app',
    measurementId: 'G-XEE2MJD50X',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAy2YSQaQ0sVTk0xs6cKaaZnpQp1qd5e5M',
    appId: '1:153738262076:android:4cf8748c027aac7e78b539',
    messagingSenderId: '153738262076',
    projectId: 'threadup-ae501',
    storageBucket: 'threadup-ae501.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCMjFzE-BsRbsuBcFo8wQwl_n2EYJ4khxQ',
    appId: '1:153738262076:ios:7fd5fa8cb17b773d78b539',
    messagingSenderId: '153738262076',
    projectId: 'threadup-ae501',
    storageBucket: 'threadup-ae501.firebasestorage.app',
    iosClientId: '153738262076-n17r10dcuf4giq2kr57bv2iiq4rjq935.apps.googleusercontent.com',
    iosBundleId: 'com.example.threadup',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCMjFzE-BsRbsuBcFo8wQwl_n2EYJ4khxQ',
    appId: '1:153738262076:ios:7fd5fa8cb17b773d78b539',
    messagingSenderId: '153738262076',
    projectId: 'threadup-ae501',
    storageBucket: 'threadup-ae501.firebasestorage.app',
    iosClientId: '153738262076-n17r10dcuf4giq2kr57bv2iiq4rjq935.apps.googleusercontent.com',
    iosBundleId: 'com.example.threadup',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyC7wdXZrTzI0ztV1loBY8wohZ9hFGpdh3A',
    appId: '1:153738262076:web:e48dde36175c20d378b539',
    messagingSenderId: '153738262076',
    projectId: 'threadup-ae501',
    authDomain: 'threadup-ae501.firebaseapp.com',
    storageBucket: 'threadup-ae501.firebasestorage.app',
    measurementId: 'G-3RYFZNLX3Y',
  );
}
